INSERT INTO DEVELOPER (NAME) VALUES ('Birol');

INSERT INTO ISSUES (TITLE, DESCRIPTION, CREATION_DATE, ASSIGNED_DEVELOPER, TYPE) VALUES ('meineerstestory','testdescriptionstories1', '2014-01-28', 1, 'STORIES');
INSERT INTO ISSUES (TITLE, DESCRIPTION, CREATION_DATE, ASSIGNED_DEVELOPER, TYPE) VALUES ('meineersterbug','testdescriptionbug2', '2014-02-02', 1, 'BUGS');