INSERT INTO DEVELOPER (NAME) VALUES ('Birol');
INSERT INTO DEVELOPER (NAME) VALUES ('Tameldo');
INSERT INTO DEVELOPER (NAME) VALUES ('Roland');
INSERT INTO DEVELOPER (NAME) VALUES ('Florian');
INSERT INTO DEVELOPER (NAME) VALUES ('Amit');
INSERT INTO DEVELOPER (NAME) VALUES ('Dan');
INSERT INTO DEVELOPER (NAME) VALUES ('Milad');

INSERT INTO ISSUES (TITLE, DESCRIPTION, CREATION_DATE, ASSIGNED_DEVELOPER, TYPE) VALUES ('meineerstestory','testdescriptionstories1', '2014-01-28', 1, 'STORIES');
INSERT INTO ISSUES (TITLE, DESCRIPTION, CREATION_DATE, ASSIGNED_DEVELOPER, TYPE) VALUES ('meineersterbug','testdescriptionbug2', '2014-02-02', 1, 'BUGS');